# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d461a96720f95a7de43633d3c33c932f619f3de332065b6af4bb818e9c7dc99236f72192fad44de339136c92d5c00c6087e0adc098b9b003cca600df6c5244

test:
  secret_key_base: d7aa197ca7282f5e3659fa5a656eba9b9e2bdf59fb55eb5b050e39cde04fc9df531811b98ef5a92f5cc23f0799038f33448160441d7f061784ad4f4a845dc0b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
